name: Terraform Validations

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Check Terraform format
        run: terraform fmt -check
        working-directory: terraform/dev # or use terraform/prod if necessary

  validate:
    needs: format_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Generate tfvars
        run: |
          for var in $(compgen -e); do
            echo "${var} = \"$(printenv ${var})\"" >> terraform.tfvars
          done
          cat terraform.tfvars
        working-directory: terraform/dev

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/dev

      - name: Terraform Validate
        run: terraform validate -var-file=terraform.tfvars
        working-directory: terraform/dev
